import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";
import LenisProvider from "@/components/LenisProvider";

const poppins = Poppins({
  subsets: ["latin"], // Choose the subsets you need
  weight: ["300", "400", "500", "600", "700"], // Specify the font weights you want
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LenisProvider>
        <body className={`${poppins.className} antialiased`}>{children}</body>
      </LenisProvider>
    </html>
  );
}
